### ISSUE TITLE
TypeError: `pad_width` must be of integral type.

### ISSUE THREAD

**Issue by yasseryasser09** [cssartori/image-dehazing#1]
after fixing all python 2 problems,
here is a problem : 

  File "main.py", line 90, in <module>
    oimg = dehaze(img.array(), a, t, rt, tmin, ps, w, px, r, eps, m)
  File "/content/image-dehazing/src/Dehaze.py", line 49, in dehaze
    jdark = DarkChannel.estimate(imgar, ps)
  File "/content/image-dehazing/src/DarkChannel.py", line 26, in estimate
    impad = numpy.pad(imgar, [(ps/2,ps/2), (ps/2,ps/2) , (0,0)], 'edge')
  File "<__array_function__ internals>", line 6, in pad
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/arraypad.py", line 745, in pad
    raise TypeError('`pad_width` must be of integral type.')
TypeError: `pad_width` must be of integral type.

**Comment by cssartori** [comment]
What "all python 2 problems" are you referring to? Are there errors when running the code using Python 2? At the time of commit to the repository, the code was working correctly using Python 2.7.

From the message you are reporting, it is indicated that you are trying to use Python 3.6, which is not the version the code was originally written for. Thus, it is expected that errors may occur when using a different version.

If you want to use Python 3.6+, I suggest to take a look at [this repository](https://github.com/tigerhawkvok/image-dehazing), which is a fork from mine but modified to work with newer versions of Python.
